services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:18.3-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pg-backup:
    image: ghcr.io/tobonator3/pg-backup-docker:18.3
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - backups:/backup
    environment:
      - TZ=Europe/Berlin
      - BACKUP_SCHEDULE=0 3 * * *
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  backups:
  db:
