services:
  postgres:
    image: pgautoupgrade/pgautoupgrade:18.1-alpine
    restart: unless-stopped
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db-backup:
    build: tobonator/postgres-backup-docker
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db
    volumes:
      - backups:/backup
    environment:
      - TZ=Europe/Berlin
      - BACKUP_SCHEDULE=0 3 * * *
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  db: { internal: true }

volumes:
  backups:
  db:
